language: python            # this works for Linux but is an error on macOS or Windows
jobs:
  include:

    - name: "Python 3.7.4 on Windows"
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell       # 'language: python' is an error on Travis CI Windows
      before_install:
        - choco install python --version 3.8.0
        - python -m pip install --upgrade pip
      env: PATH=/c/Python38:/c/Python38/Scripts:$PATH

install:
- pip3 install --upgrade pip  # all three OSes agree about 'pip3'
- pip install awscli
- pip install aws-sam-cli
- pip install chalice
- pip install virtualenv
script:
- chalice package packaged/
- ls packaged/
- cd packaged/
- aws cloudformation package --template-file ./sam.json  --s3-bucket travisci-pfizer-bucket  --output-template-file sam-packaged.yaml

deploy:
  provider: script
  region: us-east-1
  script: aws cloudformation deploy --template-file C:\Users\travis\build\hvijay1705\PfizerAWSWorkshopCICD\packaged\sam-packaged.yaml --stack-name travisci-pfizer-stack  --capabilities CAPABILITY_IAM
  skip_cleanup: true
  on:
    branch: master

notifications:
  email:
    recipients:
      - learning.hvijay1705@gmail.com
    on_success: always # default: change
    on_failure: always # default: always