language: python            # this works for Linux but is an error on macOS or Windows
jobs:
  include:

    - name: "Python 3.7.4 on Windows"
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell       # 'language: python' is an error on Travis CI Windows
      before_install:
        - choco install python --version 3.8.0
        - python -m pip install --upgrade pip
      env: PATH=/c/Python38:/c/Python38/Scripts:$PATH
install: pip3 install --upgrade pip  # all three OSes agree about 'pip3'
notifications:
  email:
    recipients:
      - learning.hvijay1705@gmail.com
    on_success: never # default: change
    on_failure: always # default: always